[package]
name = "bevy_poly_navmesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_pathmesh = "0.5.0"
parry3d = "0.13.5"
polyanya = "0.4.0"
spade = "2.2.0"
